zh_CN: &zh
  0: "成功"
  -1: "失败"
  40001: "资源不存在"
  40002: "参数无效"
  40003: "账户或密码错误"
  40004: "验证码错误"
  40005: "请登陆"
  40006: "微信授权失败"
  40007: "验证码过期"
  40008: "手机号错误"
  40009: "操作频繁,请稍后再试:"

en:
  <<: *zh
  # 英文编码
  0: "success"
  -1: "fail"
  40001: "No resources found"
  40002: "Invalid argument"
  40003: "Incorrect account or password"
  40004: "Verification code error"
  40005: "Please sign in"
  40006: "WeChat Authorization Failure"
  40007: "Verification code expired"
  40008: "Mobile number error"
  40009: "Frequent operation, please try again late"